### ISSUE TITLE
location is undefined here and I'm not sure what the proper input should be

### ISSUE THREAD

**Issue by palewire** [biglocalnews/court-scraper#113]
https://github.com/biglocalnews/court-scraper/blob/f89b86d07d39d99c8c123717227fbc773d4933c3/court_scraper/base/parse.py#L54

**Comment by zstumgoren** [comment]
@palewire Heads up that we're doing some house-cleaning prior to v0.1.0 release and this file is going to be deleted as part of #96. Hoping to drop that release by end of week. Would love a once-over after we've merged and released changes. You can see what's on the menu by checking out tix flagged with the [v0.1.0. milestone](https://github.com/biglocalnews/court-scraper/issues?q=is%3Aopen+is%3Aissue+milestone%3Av0.1.0)
