### ISSUE TITLE
Ditch Travis and cut over to GH Actions for builds?

### ISSUE THREAD

**Issue by zstumgoren** [biglocalnews/court-scraper#124]
The GH Actions CI builds, courtesy of @palewire, are passing for Python 3.6-3.9 now that a minor test config issue has been fixed. Meanwhile, Travis build is failing on python 3.6 due to a gnarly little build error related to the cryptography library #123. 

Should we ditch Travis and just pot-commit to GH Actions?

If so, need to:

- [ ] Delete .travis.yml
- [ ] Do a careful once-over on docs and code to make sure we update all preexisting badges and add badges anywhere else that's appropriate. Files we know will need updates are: README.md,  README.rst, setup.py (which uses an embedded rst doc string)

**Comment by palewire** [comment]
I would vote yes here. Actions has more features, is growing fast, is more closely tied to your code.
