### ISSUE TITLE
OK_dev branch refactorings

### ISSUE THREAD

**Issue by zstumgoren** [biglocalnews/court-scraper#33]
Misc. list of fixes for `ok_dev` branch:

- [x] Remove all underscores from module names and make class names mirror module name using singular, CamelCase 
- [x] [`selenium_base.py`](https://github.com/biglocalnews/court-scraper/blob/ok_dev/court_scraper/base/selenium_base.py) only appears to contain a SeleniumPage class. Unclear if this is now obsolete. If still in use, relocate and/or rename so class and module name align
- [x] OSCN platform doesn't appear to have a Site class and is missing an `__init__.py` in [platforms/oscn](https://github.com/biglocalnews/court-scraper/tree/ok_dev/court_scraper/platforms/oscn)
- [x] [sites_meta.csv](https://github.com/biglocalnews/court-scraper/blob/ok_dev/court_scraper/data/sites_meta.csv) - remove strings from urls in OK and WI and sort data by state postal and county
- [oscn/pages/config.py](https://github.com/biglocalnews/court-scraper/blob/ok_dev/court_scraper/platforms/oscn/pages/config.py) contains URLs. Should rename this module to more clearly express usage, or move the class to a more appropriate location
- [base._search_page_mixin](https://github.com/biglocalnews/court-scraper/blob/ok_dev/court_scraper/base/_search_page_mixin.py) appears to contains code that is specific to OK rather than purely generic. Seems like this code likely belongs in an OK Site class
- [base/_selenium_site_search_mixin.py](https://github.com/biglocalnews/court-scraper/blob/ok_dev/court_scraper/base/_selenium_site_search_mixin.py) appears to contain code extracted from the Odyssey Platform, which was originally written for GA court sites. It appears this code is being used for WI sites. Is that correct? If so, we should rename the SiteSearchMixin class and containing module and possibly relocate it as the current naming/location in `base` gives the sense that the code is broadly generic (code in `base` is intended to be widely applicable). for example, it may be more appropriate to put this code in a base dir/modules inside of the Odyssey Platform

**Comment by ryanelittle** [comment]
I believe that I have addressed every issue but one in this ticket. My search_page_mixin is not OK-specific. I explain further below. I also propose removing [base/seleniun_site_search_mixin.py](https://github.com/biglocalnews/court-scraper/blob/ok_dev/court_scraper/base/_selenium_site_search_mixin.py) as it exists in this branch but could use some direction on how to provide that functionality.

- [base/search_page_mixin](https://github.com/biglocalnews/court-scraper/blob/ok_dev/court_scraper/base/_search_page_mixin.py) is all generic code that assumes a case abbreviation submitted by the user/developer exists on the page. So far, I have never seen a court website system that would not pass this test. The search_page_mixin is written in a way that both Selenium and Requests can use them to return the last date. In fact, both Oklahoma and Wisconsin rely on this class to provide that functionality.

-[base/seleniun_site_search_mixin.py](https://github.com/biglocalnews/court-scraper/blob/ok_dev/court_scraper/base/_selenium_site_search_mixin.py) is not a class I am actually utilizing at the moment. I am also pretty sure that it is base functionality I need to provide to the CLI that I currently am not. Is that right?
