### ISSUE TITLE
Add Sonoma County cli support

### ISSUE THREAD

**Issue by DiPierro** [biglocalnews/court-scraper#80]
Sonoma County, CA uses Odyssey: https://cmsportal.sonomacourt.org/IPortal/

- [x] Sonoma requires a CAPTCHA. Should check to see if we can register to bypass CAPTCHAs
- [x] Add to `sites_meta.csv` to expose via CLI.

**Comment by zstumgoren** [comment]
I registered for Sonoma. After verifying email and attempting to log in I received the below error notice:

```
Your account has not been authorized to use this site. Please contact the court.
```

Not clear to me if we need to await admin approval or if this is some vestigal registration feature that is no longer supported...
